openapi: 3.0.0

info:
  title: Malicious URL Scanner API
  description: Real-time scanning of URLs to detect malicious activity and assess the reputation of domains.
  version: "v1"

servers:
  - url: https://ipqualityscore.com/api/json/url

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: IPQS-KEY

paths:
  /:
    get:
      operationId: ScanURL
      summary: Scan a URL and get the results
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
          description: The URL to be scanned, i.e. www.google.com
        # Add other query parameters as needed
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
        - ApiKeyAuth: []